service: burguesesbot

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}
    WEBHOOK_SECRET_PATH: ${env:WEBHOOK_SECRET_PATH}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  webhook:
    handler: dist/main-serverless.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'


# package:
#   exclude:
#     - .git/**
#     - .serverless/**
#     - node_modules/**
#     - src/**
#     - test/**
#     - .env*
#     - .eslintrc.js
#     - .gitignore
#     - .prettierrc
#     - LICENSE
#     - README.md
#     - tsconfig.build.json
#     - tsconfig.json
