name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/default.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      pull-requests: write
      statuses: write 
      deployments: write
      checks: write
