name: Python CI

on:
  push:
    branches: [ main, recreation-from-scratch, feat/issue-66-poetry-monoranger ]
  pull_request:
    branches: [ main, recreation-from-scratch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Smoke test
        run: |
          python -c "import sys; print('python-ok', sys.version)"
